# https://github.com/compose-spec/compose-spec/blob/master/spec.md

version: '3.8'

services:
  db:
    container_name: igeg-postgresql
    image: postgres:14.1-alpine
    restart: "no"
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - PD_DATA:/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
